/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JFrame;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import  Controller.Operaciones;

public class IFrmEstadisticasSaludFisica extends javax.swing.JInternalFrame {

    JFreeChart Grafica;
    DefaultCategoryDataset Dato = new DefaultCategoryDataset();
    public Operaciones op;
    
    public IFrmEstadisticasSaludFisica() {
        op = new Operaciones();
        initComponents();
    }

    public DefaultCategoryDataset GraficaSaludFisica() {
        
        //while (op.DatosGraf != null) {

            Dato.addValue(/*op.DatosGraf.PesoOptimo1*/2, "Peso Optimo", "1-10 año(s)");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/0, "Peso Optimo", "11-20 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/1, "Peso Optimo", "21-30 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/6, "Peso Optimo", "31-40 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/5, "Peso Optimo", "41-50 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/1, "Peso Optimo", "51-60 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/6, "Peso Optimo", "61-70 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/0, "Peso Optimo", "71-80 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/0, "Peso Optimo", "81-90 años");
            
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/0, "Sobre Peso", "1-10 año(s)");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/1, "Sobre Peso", "11-20 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/3, "Sobre Peso", "21-30 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/4, "Sobre Peso", "31-40 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/9, "Sobre Peso", "41-50 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/4, "Sobre Peso", "51-60 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/0, "Sobre Peso", "61-70 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/0, "Sobre Peso", "71-80 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/0, "Sobre Peso", "81-90 años");

            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/1, "Peso por Debajo", "1-10 año(s)");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/1, "Peso por Debajo", "11-20 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/1, "Peso por Debajo", "21-30 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/2, "Peso por Debajo", "31-40 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/5, "Peso por Debajo", "41-50 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/3, "Peso por Debajo", "51-60 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/2, "Peso por Debajo", "61-70 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/2, "Peso por Debajo", "71-80 años");
            Dato.addValue(/*op.DatosGraf.PesoOptimo2*/3, "Peso por Debajo", "81-90 años");
            
         //   op.DatosGraf = op.DatosGraf.sig;
       //}
        return Dato;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollBar1 = new javax.swing.JScrollBar();
        jCheckBox2 = new javax.swing.JCheckBox();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jPopupMenu6 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenu7.setText("File");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar2.add(jMenu8);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Estadistica de Salud Fisica");

        jButton3.setText("GRAFICA PESOS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Grafica = ChartFactory.createBarChart3D("GRAFICA DE PESO ", " RANGO DE EDADES", "CANTIDAD DE PERSONAS",
                 GraficaSaludFisica(), PlotOrientation.VERTICAL, true, true, false);
        ChartPanel Panel = new ChartPanel(Grafica);
        JFrame Ventana;
        Ventana = new JFrame("Grafica de pesos en general.");
        Ventana.getContentPane().add(Panel);
        Ventana.pack();
        Ventana.setVisible(true);
        Ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JPopupMenu jPopupMenu6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables

}
